repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.97.3  # Latest version as of 2025
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
      - id: terraform_docs
        args: ["markdown", "README.md"]
  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v6.20.0  # Use latest stable version
    hooks:
      - id: ansible-lint
