repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.97.3  # Latest version as of 2025
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
      - id: terraform_docs
        args: ["markdown", "README.md"]

